ship_o_cereal/cart/urls.py
from django.urls import path
from . import views
from cereal.views import updatecart
urlpatterns = [
    # http://localhost:8000/cart
    path('', views.index, name="cart-index"),
    path('update_cart/', updatecart, name="update-cart")

]

ship_o_cereal/ship_o_cereal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('front_page.urls')),
    path('admin/', admin.site.urls),
    # path('cereals/', include('cereal.urls')),
    path('products/', include('cereal.urls')),
    path('merch/', include('merch.urls')),
    path('users/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('aboutus/', include('about_us.urls')),
]

ship_o_cereal/cereal/models.py
from django.db import models

# Create your models here.


# Model that keeps all the products
class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=999, blank=True)
    brand = models.CharField(max_length=255, blank=True)
    tags = models.CharField(max_length=999, blank=True)
    price = models.FloatField()


# Model that references products and keeps all images relating to products
# as a string (link) to image
class CerealImage(models.Model):
    image = models.CharField(max_length=9999)
    cereal = models.ForeignKey(Product, on_delete=models.CASCADE)

ship_o_cereal/templates/products/list_display.html
{% load static %}

<div class="col mb-4">
    <div class="card shadow">

        <a href="{{ product.name }}">
            <img class="card-img-top p-3 list_img" src="{{ product.cerealimage_set.first.image }}"
                 alt="{{ product.name }}">

        </a>

<!--        <img src="{% static 'images/'|add:product.name|add:'.jpeg' %}" class="card-img-top p-3" alt="{{ product.name }}">-->
        <!--Card content-->
        <div class="card-body">
            <!--Title-->
            <h4 class="card-title">{{ product.name }}</h4>
            <!--Text-->
            <p class="card-text">{{ product.description }}</p>
            <!--Price-->
            <h5 class="card-title">{{ product.price|floatformat:0 }} ISK</h5>
            <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
            <a href="{{ product.name }}" class="btn btn-primary">Info</a>
            <a data-product="{{ product.id }}" data-action="add" class="btn btn-success btn-inline update-cart" >
                <i class="fas fa-cart-plus"></i>
            </a>
        </div>
    </div>
</div>

ship_o_cereal/templates/products/single_product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

{# Displays a single product page #}

<div class="container my-5 py-5 z-depth-1">


  <!--Section: Content-->
  <section class="text-center">

    <!-- Section heading -->
    <h3 class="font-weight-bold mb-5">Product Details</h3>

    <div class="row">

      <div class="col-lg-6">

        <!--Carousel Wrapper-->
        <div id="carousel-thumb" class="carousel slide carousel-fade carousel-thumbnails" data-ride="carousel">
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
            </ul>
          <!--Slides-->
          <div class="carousel-inner text-center text-md-left" role="listbox">
            <div class="carousel-item active">
              <img src="{{ product.cerealimage_set.first.image }}"
                alt="First slide" class="img-fluid">
            </div>
            <div class="carousel-item">
              <img src="{{ product.cerealimage_set.last.image }}"
                alt="Second slide" class="img-fluid">
            </div>
          </div>
          <!--/.Slides-->

          <!--Thumbnails-->
          <a class="carousel-control-prev" href="#carousel-thumb" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon p-3 bg-dark" aria-hidden="true"></span>
{#            <span class="sr-only">Previous</span>#}
          </a>
          <a class="carousel-control-next" href="#carousel-thumb" role="button" data-slide="next">
            <span class="carousel-control-next-icon p-3 bg-dark" aria-hidden="true"></span>
{#            <span class="sr-only">Next</span>#}
          </a>
          <!--/.Thumbnails-->

        </div>
        <!--/.Carousel Wrapper-->

      </div>

      <div class="col-lg-5 text-center text-md-left">

        <h2 class="h2-responsive text-center text-md-left product-name font-weight-bold dark-grey-text mb-5 ml-xl-0 ml-4">
          <strong>{{ product.name }}</strong>
        </h2>


        <!--Accordion wrapper-->
        <div class="accordion md-accordion" id="accordionEx" role="tablist" aria-multiselectable="true">

          <!-- Accordion card -->
          <div class="card">

            <!-- Card header -->
            <div class="card-header" role="tab" id="headingOne1">
              <a data-toggle="collapse" data-parent="#accordionEx" href="#collapseOne1" aria-expanded="true"
                aria-controls="collapseOne1">
                <h5 class="mb-0">
                  Description
                  <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>

            <!-- Card body -->
            <div id="collapseOne1" class="collapse show" role="tabpanel" aria-labelledby="headingOne1"
              data-parent="#accordionEx">
              <div class="card-body">
                {{ product.description }}
              </div>
            </div>
          </div>
          <!-- Accordion card -->

          <!-- Accordion card -->
          <div class="card">

            <!-- Card header -->
            <div class="card-header" role="tab" id="headingTwo2">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseTwo2"
                aria-expanded="false" aria-controls="collapseTwo2">
                <h5 class="mb-0">
                  Details
                  <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>

            <!-- Card body -->
            <div id="collapseTwo2" class="collapse" role="tabpanel" aria-labelledby="headingTwo2"
              data-parent="#accordionEx">
              <div class="card-body">
                Ready-to-eat breakfast cereals are of four basic types: flaked, made from corn, wheat, or rice that has been broken
                  down into grits, cooked with flavours and syrups, and then pressed into flakes between cooled rollers;
                  puffed, made by exploding cooked wheat or rice from a pressure chamber, thus expanding the grain to several times
                  its original size; shredded, made from pressure-cooked wheat that is squeezed into strands by heavy rollers,
                  then cut into biscuits and dried; and granular, made by a process in which a stiff dough made from wheat and
                  malted barley flour, salt, yeast, and water is fermented, baked thoroughly, and then, after being crumbled
                  and rebaked, is ground into rough grains. As a final step in each process, the cereal is treated to restore
                  vitamins lost through cooking and often coated with sweet flavouring.
              </div>
            </div>
          </div>
          <!-- Accordion card -->

          <!-- Accordion card -->
          <div class="card">

            <!-- Card header -->
            <div class="card-header" role="tab" id="headingThree3">
              <a class="collapsed" data-toggle="collapse" data-parent="#accordionEx" href="#collapseThree3"
                aria-expanded="false" aria-controls="collapseThree3">
                <h5 class="mb-0">
                  Shipping
                  <i class="fas fa-angle-down rotate-icon"></i>
                </h5>
              </a>
            </div>

            <!-- Card body -->
            <div id="collapseThree3" class="collapse" role="tabpanel" aria-labelledby="headingThree3"
              data-parent="#accordionEx">
              <div class="card-body">
                <b>Where do we ship?</b>
                  <i>We ship only to every country in the world</i><br />
                  <b>How much is shipping?</b>
                   <i>Shipping is free within to the EU and to North Korea</i><br />
                  <b>How long does it take?</b>
                  <i>It will appear instantly at your doorstep as soon as your payment is done</i><br />
              </div>
            </div>
          </div>
          <!-- Accordion card -->

        </div>
        <!--/.Accordion wrapper-->


            <h3 class="h3-responsive text-center text-md-right my-5 ml-xl-0 ml-4">
                <strong>{{ product.price|floatformat:0 }} ISK</strong>

            </h3>
            <div class="row mt-3">
              <div class="col-md-12 text-center text-md-left text-md-right">
                <button data-product={{ product.id }} data-action="add"  class="btn btn-success btn-rounded update-cart">
                  <i class="fas fa-cart-plus mr-2" aria-hidden="true"></i> Add to cart
                </button>

              </div>
            </div>


      </div>

    </div>

  </section>
  <!--Section: Content-->


</div>

{% endblock %}