ship_o_cereal/cart/urls.py
from django.urls import path
from . import views
from cereal.views import updatecart
urlpatterns = [
    # http://localhost:8000/cart
    path('', views.index, name="cart-index"),
    path('update_cart/', updatecart, name="update-cart")

]

ship_o_cereal/ship_o_cereal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('front_page.urls')),
    path('admin/', admin.site.urls),
    # path('cereals/', include('cereal.urls')),
    path('products/', include('cereal.urls')),
    path('merch/', include('merch.urls')),
    path('users/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('checkout/', include('checkout.urls')),
    path('aboutus/', include('about_us.urls')),
]

ship_o_cereal/user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

urlpatterns = [
    # http://localhost:8000/users
    path('', views.profile, name="profile-index"),
    path('edit', views.edit_profile, name="user-edit"),
    path('wishlist', views.wish, name="user-wishlist"),
    path('change_pic', views.change_pic, name="user-pic"),
    path('change_pw', views.change_pw, name="change-pw"),
    path('add_hist', views.update_search_history, name="add-hist"),
    path('get_hist', views.get_search_history, name="get-hist"),


]

ship_o_cereal/user/models.py
from django.db import models
from cereal.models import Product
from django.db.models.signals import post_save
from django.contrib.auth.models import User

# Create your models here.


class SearchHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class SearchedItem(models.Model):
    searchHistory = models.ForeignKey(SearchHistory, on_delete=models.SET_NULL, blank=True, null=True)
    searchItem = models.CharField(max_length=255, null=True, blank=True)


# make_profile creates a entry in the user_profile table connected to user created
class Profile(models.Model):
    user = models.OneToOneField(User, related_name='Profile', on_delete=models.CASCADE)
    profile_img = models.CharField(max_length=9999, default="https://img.icons8.com/material-rounded/200/000000/user.png")

    def make_profile(sender, **kwargs):
        user = kwargs["instance"]
        if kwargs["created"]:
            user_profile = Profile(user=user)
            user_profile.save()
    post_save.connect(make_profile, sender=User)

    def __str__(self):
        return str(self.id)

ship_o_cereal/user/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth.models import User
from django.forms import ModelForm, widgets
from .models import Profile


class TheProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['id', 'user']
        widgets = {
            'profile_img': widgets.TextInput(attrs={'class': 'form-control'})
        }


class ImprovedUserChangeForm(UserChangeForm):
    class Meta:
        model = User
        exclude = ['id', 'last_login', 'is_superuser', 'groups', 'is_staff', 'is_active', 'password',
                   'user_permissions', 'date_joined']
        widgets = {
            'username': widgets.TextInput(attrs={'class': 'form-control'}),
            'first_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'last_name': widgets.TextInput(attrs={'class': 'form-control'}),
            'email': widgets.TextInput(attrs={'class': 'form-control'})
        }


class ChangePicForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ['id', 'user']
        widgets = {
            'profile_img': widgets.TextInput(attrs={'class': 'form-control'})
        }

ship_o_cereal/user/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from .models import Profile, SearchHistory, SearchedItem
from django.contrib import messages
from .forms import (
    TheProfileForm,
    ImprovedUserChangeForm,
    ChangePicForm)




def index(request):
    return render(request, 'user/index.html')


def item(request):
    return render(request, 'user/edit_profile.html')


def wish(request):
    return render(request, 'user/wishlist.html')


@login_required
def profile(request):
    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = TheProfileForm(instance=profile, data=request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            return redirect('profile-index')
    return render(request, 'user/index.html', {
        'form': TheProfileForm(instance=profile)
    })

# View to edit user profile.
@login_required
def edit_profile(request):
    if request.method == 'POST':
        form = ImprovedUserChangeForm(instance=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated!')
            return redirect('profile-index')
    else:
        form = ImprovedUserChangeForm(instance=request.user)
    return render(request, 'user/edit_profile.html', {'form': form})

# View to change the profile picture for the user
@login_required
def change_pic(request):
    profile = Profile.objects.filter(user=request.user).first()
    if request.method == 'POST':
        form = ChangePicForm(instance=profile, data=request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = request.user
            profile.save()
            messages.success(request, 'Profile picture updated, nice one!')
            return redirect('user-pic')
    return render(request, 'user/change_pic.html', {
        'form': ChangePicForm(instance=profile)
    })


# View to change the password for the user, the user does not log out if the password change is successful
@login_required
def change_pw(request):
    if request.method == 'POST':
        form = PasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, f'New password confirmed')
            return redirect('profile-index')
    else:
        form = PasswordChangeForm(user=request.user)
    return render(request, 'user/change_pw.html', {'form': form})



# inserts search string into users search history (except for empty strings)
def update_search_history(request):
    data = json.loads(request.body)
    search_string = data['search_string']
    if request.user.is_authenticated and search_string != "":
        searchhistory, create = SearchHistory.objects.get_or_create(user=request.user)
        searcheditem = SearchedItem.objects.create(searchHistory=searchhistory, searchItem=search_string)
        searcheditem.searchItem = search_string
        searchhistory.save()
        searcheditem.save()
        return JsonResponse('Item was added', safe=False)
    else:
        return JsonResponse({'data': ""})

# returns users search history (5 most recent searches)
def get_search_history(request):
    if request.user.is_authenticated:
        searchhistory, created = SearchHistory.objects.get_or_create(user=request.user)
        items = searchhistory.searcheditem_set.values('searchItem')
        data = list(items)
        data.reverse()
        return JsonResponse({'data': data[:5]})
    else:
        items = []
        return JsonResponse({'data': items})

ship_o_cereal/templates/user/change_pic.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <br>
    <div class="container">
        <img src="{{ user.Profile.profile_img }}" class="rounded-circle w-25 p-3">
    </div>
    <br>
    <form class="form form-horizontal" method="post">
        {% csrf_token %}
        <tr><th><label for="id_profile_img">Please paste image url:</label></th><br><td><input type="text" name="profile_img" value="{{ user.Profile.profile_img }}" class="form-control" maxlength="9999" required id="id_profile_img"></td></tr><br>
        <input type="submit" class="btn btn-info btn-block my-4" value="Save changes" />
        <a href="{% url "profile-index" %}" class="btn btn-block btn-outline-success my-4">Go back</a>

    </form>

{% endblock %}

ship_o_cereal/templates/user/change_pw.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <br>
    <br>
    <form class="form form-horizontal" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" class="btn btn-info btn-block my-4" value="Save changes" />
        <a href="{% url "profile-index" %}" class="btn btn-block btn-outline-success my-4">Go back</a>

    </form>

{% endblock %}

ship_o_cereal/templates/user/edit_profile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-info btn-block my-4" value="Save changes" />
        </form>
        <a href="{% url "profile-index" %}" class="btn btn-block btn-outline-success my-4">Go back</a>
    </div>
{% endblock %}

ship_o_cereal/templates/user/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1> Welcome to your profile {{ user.first_name }} {{ user.last_name }}!</h1>
    <div class="container">
        <img src="{{ user.Profile.profile_img }}" class="rounded-circle w-25 p-3">
        <div class="d-inline-block">
            <a href="{% url "user-edit" %}" class="btn btn-info my-2 my-sm-0">Edit profile</a>
            <a href="{% url "change-pw" %}" class="btn btn-info my-2 my-sm-0">Change password</a>
            <a href="{% url "user-pic" %}" class="btn btn-info my-2 my-sm-0">Change profile picture</a>
        </div>

    </div>
{% endblock %}

ship_o_cereal/templates/user/wishlist.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h1>Your wishlist</h1>
{% endblock %}